server:
  port: 8080
  servlet:
    context-path: /identity-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/identity_service_db?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
jwt:
  signerKey: "fa59838d080c4a0c3cad5699b0e9c2f3e3077e2d9e6158b5dbd4ea3eb65cdd2a"
app:
  init-data: true