server:
  port: 8080
  servlet:
    context-path: /identity-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/identity_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

