server:
  port: 8080
  servlet:
    context-path: /identity-service

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:identity_service_db}?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: ${JWT_KEY}
app:
  init-data: true
