services:
  identity-db:
    image: postgres:17
    container_name: identity-db
    restart: always
    environment:
      POSTGRES_DB: identity_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d identity_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  identity-backend:
    build: .
    container_name: identity-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=identity-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - jwt.signerKey=${JWT_KEY}
      - server.servlet.context-path=/identity-service
      -
    depends_on:
      identity-db:
        condition: service_healthy

volumes:
  postgres_data: